#!/usr/bin/env bash
# This script print "Best School" 10 times and print "hi" after 9 times using while loops
n=1
while [ $n -le 10 ]; do
	echo "Best School"
	if [ $n == 9 ]; then
		echo "Hi"
	fi
	n=$((n+1))
done
