#!/usr/bin/env bash
# script displays the time
hour=0
while [ "$hour" -le 12 ]; do
	minute=1
	echo "Hour: $hour"
	while [ "$minute" -lt 60 ]; do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
